# Pre-commit hooks configuration for AI Finance Manager
# See https://pre-commit.com for more information

repos:
  # Python backend hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^finance-dashboard/
      - id: end-of-file-fixer
        exclude: ^finance-dashboard/
      - id: check-yaml
        exclude: ^finance-dashboard/
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
        files: ^backend/.*\.py$

  # Python formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^backend/.*\.py$
        language_version: python3

  # Python import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^backend/.*\.py$
        args: ["--profile", "black"]

  # Python linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        files: ^backend/.*\.py$
        args: [
          "--max-line-length=88",
          "--extend-ignore=E203,W503,E501"
        ]

  # Python security check with bandit
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        files: ^backend/.*\.py$
        args: ["-r", "--skip", "B101,B601"]

  # TypeScript/JavaScript frontend hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        files: ^finance-dashboard/.*\.(ts|tsx|js|jsx)$
        types_or: [typescript, javascript]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@^8.0.0"
          - "@typescript-eslint/parser@^8.0.0"
          - "eslint@^9.0.0"
          - "eslint-plugin-react@^7.35.0"
          - "eslint-plugin-react-hooks@^4.6.0"
        args: ["--fix"]

  # Prettier for frontend formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^finance-dashboard/.*\.(ts|tsx|js|jsx|json|css|md)$
        args: ["--write"]

  # General hooks for all files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Docker hooks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

  # Secrets detection
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.87.0
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail'
        language: system
        stages: ["commit", "push"]