version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-finance-postgres
    environment:
      POSTGRES_DB: ai_finance_db
      POSTGRES_USER: ai_finance_user
      POSTGRES_PASSWORD: ai_finance_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai-finance-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_finance_user -d ai_finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ai-finance-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aifinance.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ai-finance-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ai-finance-network:
    driver: bridge