"""Add multi-currency support to expenses

Revision ID: 4781a7876a6e
Revises: cfa2a1b5a332
Create Date: 2025-07-23 18:41:15.960072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4781a7876a6e'
down_revision: Union[str, Sequence[str], None] = 'cfa2a1b5a332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add original_currency column with default value first
    op.add_column('expenses', sa.Column('original_currency', sa.String(), nullable=True, server_default='EUR'))
    
    # Update existing records to have EUR as default currency
    op.execute("UPDATE expenses SET original_currency = 'EUR' WHERE original_currency IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('expenses', 'original_currency', nullable=False)
    
    # Remove the server default since we don't want it for future inserts
    op.alter_column('expenses', 'original_currency', server_default=None)
    
    # Add other currency columns
    op.add_column('expenses', sa.Column('amounts', sa.JSON(), nullable=True))
    op.add_column('expenses', sa.Column('exchange_rates', sa.JSON(), nullable=True))
    op.add_column('expenses', sa.Column('exchange_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'exchange_date')
    op.drop_column('expenses', 'exchange_rates')
    op.drop_column('expenses', 'amounts')
    op.drop_column('expenses', 'original_currency')
    # ### end Alembic commands ###
