"""drop_receipt_items_table

Revision ID: 57c1690e1bb3
Revises: f2eb6f4a580b
Create Date: 2025-12-26 04:47:51.097617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57c1690e1bb3'
down_revision: Union[str, None] = 'f2eb6f4a580b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_items_receipt_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name=op.f('receipt_items_receipt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('receipt_items_pkey'))
    )
    op.create_index(op.f('ix_receipt_items_receipt_id'), 'receipt_items', ['receipt_id'], unique=False)
    # ### end Alembic commands ###
