"""add 
  belvo-integration 
  source to expense 
  enum

Revision ID: 71e6c1fba518
Revises: 83de3e2d2ac8
Create Date: 2025-07-26 12:45:19.136787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e6c1fba518'
down_revision: Union[str, Sequence[str], None] = '83de3e2d2ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('belvo_institutions_belvo_id_key'), 'belvo_institutions', type_='unique')
    op.drop_index(op.f('ix_belvo_institutions_belvo_id'), table_name='belvo_institutions')
    op.create_index(op.f('ix_belvo_institutions_belvo_id'), 'belvo_institutions', ['belvo_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_belvo_institutions_belvo_id'), table_name='belvo_institutions')
    op.create_index(op.f('ix_belvo_institutions_belvo_id'), 'belvo_institutions', ['belvo_id'], unique=False)
    op.create_unique_constraint(op.f('belvo_institutions_belvo_id_key'), 'belvo_institutions', ['belvo_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
