"""add
   belvo-integration source to expense 
  enum

Revision ID: 763d2855fd0b
Revises: 71e6c1fba518
Create Date: 2025-07-26 12:55:51.945532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763d2855fd0b'
down_revision: Union[str, Sequence[str], None] = '71e6c1fba518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
