"""add_converted_amounts_to_expenses

Revision ID: 90b397ad8ca4
Revises: 57c1690e1bb3
Create Date: 2025-12-26 09:07:25.021215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b397ad8ca4'
down_revision: Union[str, None] = '57c1690e1bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('amount_eur', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('amount_brl', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'amount_brl')
    op.drop_column('expenses', 'amount_eur')
    op.drop_column('expenses', 'amount_usd')
    # ### end Alembic commands ###
