"""Make expense_date nullable

Revision ID: d372ff9cfea3
Revises: 75f875f91ea9
Create Date: 2026-01-25 05:36:44.895935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd372ff9cfea3'
down_revision: Union[str, None] = '75f875f91ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'expense_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_user_category_preferences_lookup'), table_name='user_category_preferences')
    op.create_index(op.f('ix_user_category_preferences_item_name_pattern'), 'user_category_preferences', ['item_name_pattern'], unique=False)
    op.create_index(op.f('ix_user_category_preferences_store_name_pattern'), 'user_category_preferences', ['store_name_pattern'], unique=False)
    op.drop_constraint(op.f('user_category_preferences_user_id_fkey'), 'user_category_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'user_category_preferences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_category_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('user_category_preferences_user_id_fkey'), 'user_category_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_category_preferences_store_name_pattern'), table_name='user_category_preferences')
    op.drop_index(op.f('ix_user_category_preferences_item_name_pattern'), table_name='user_category_preferences')
    op.create_index(op.f('ix_user_category_preferences_lookup'), 'user_category_preferences', ['user_id', 'item_name_pattern'], unique=False)
    op.alter_column('expenses', 'expense_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
