"""create_users_table

Revision ID: ffb3c20ff942
Revises: 001_initial_integration_tables
Create Date: 2025-07-28 11:17:34.541986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb3c20ff942'
down_revision: Union[str, Sequence[str], None] = '001_initial_integration_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('connected_accounts_id_idx'), 'connected_accounts', ['id'], unique=False)
    op.create_index(op.f('integrations_id_idx'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('sync_logs_id_idx'), 'sync_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('sync_logs_id_idx'), table_name='sync_logs')
    op.drop_index(op.f('integrations_id_idx'), table_name='integrations')
    op.drop_index(op.f('connected_accounts_id_idx'), table_name='connected_accounts')
    # ### end Alembic commands ###
